#!/bin/sh
set -e

cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies…"
bundle check --path vendor/gems 2>&1 > /dev/null || {
  bundle install --path vendor/gems --quiet --without production
}
